### ISSUE TITLE
In mobile view, hide/fade sticky radar graphic until after the first card

### ISSUE THREAD

**Issue by colinmorris** [colinmorris/atypicality#14]

**Comment by colinmorris** [comment]
(Actually this might be nice to do in desktop mode too)

**Comment by peterwgnd** [comment]
Was looking at this but was somewhat afraid to mess with it too much as I broke it in my first attempt, but I'd like to move the first two paragraphs before the "sonic reveal" section ("the authors analyzed..." and "Let's go over those features..." That way we'll flag what about to happen before people get into this section

**Comment by colinmorris** [comment]
Sure, I can definitely do that.

**Comment by colinmorris** [comment]
I just pushed some changes which I think address this. You can see for yourself, but basically, the first two paras remain floated to the right column (on desktop), but the chart only comes into view after scrolling past the first para. 

I think I like this better than moving the first two paras above the story scene, but I'm still open to trying that (or other approaches) if you want
